// <auto-generated />
using CoffeeShopp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShopp.Migrations
{
    [DbContext(typeof(CoffeeShopDbContext))]
    partial class CoffeeShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShopp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "A rich and intense shot of coffee that delivers bold flavor and instant energy.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1669687924558-386bff1a0469?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZXNwcmVzc298ZW58MHx8MHx8fDA%3D",
                            IsTrendingProduct = true,
                            Name = "Espresso",
                            Price = 20m
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Smooth espresso with steamed milk and a hint of vanilla for a creamy delight.",
                            ImageUrl = "https://images.unsplash.com/photo-1489866492941-15d60bdaa7e0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZXNwcmVzc298ZW58MHx8MHx8fDA%3D",
                            IsTrendingProduct = false,
                            Name = "Vanilla Latte",
                            Price = 27m
                        },
                        new
                        {
                            Id = 3,
                            Detail = "A layered espresso drink with sweet caramel drizzle and a creamy foam finish.",
                            ImageUrl = "https://images.unsplash.com/photo-1530878092547-647df23b3056?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZXNwcmVzc298ZW58MHx8MHx8fDA%3D",
                            IsTrendingProduct = true,
                            Name = "Caramel Macchiato",
                            Price = 30m
                        },
                        new
                        {
                            Id = 4,
                            Detail = "Classic cappuccino with a sweet, nutty hazelnut twist.",
                            ImageUrl = "https://images.unsplash.com/photo-1603145733146-ae562a55031e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGVzcHJlc3NvfGVufDB8fDB8fHww",
                            IsTrendingProduct = false,
                            Name = "Hazelnut Cappuccino",
                            Price = 22m
                        },
                        new
                        {
                            Id = 5,
                            Detail = "Earthy matcha green tea blended with creamy steamed milk for a unique flavor.",
                            ImageUrl = "https://images.unsplash.com/photo-1576618148400-71c0c252f3c9",
                            IsTrendingProduct = true,
                            Name = "Matcha Latte",
                            Price = 28m
                        },
                        new
                        {
                            Id = 6,
                            Detail = "Rich espresso paired with almond milk and a touch of honey for a naturally sweetened drink.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1723741247155-38ea929d6998?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGVzcHJlc3NvfGVufDB8fDB8fHww",
                            IsTrendingProduct = false,
                            Name = "Honey Almond Flat White",
                            Price = 25m
                        },
                        new
                        {
                            Id = 7,
                            Detail = "A spicy-sweet blend of black tea and spices with steamed milk for a comforting beverage.",
                            ImageUrl = "https://images.unsplash.com/photo-1523063308874-cecc260a3171?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGVzcHJlc3NvfGVufDB8fDB8fHww",
                            IsTrendingProduct = true,
                            Name = "Chai Tea Latte",
                            Price = 18m
                        },
                        new
                        {
                            Id = 8,
                            Detail = "Freshly brewed coffee chilled and served over ice, perfect for hot days.",
                            ImageUrl = "https://images.unsplash.com/photo-1508088405209-fbd63b6a4f50?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGVzcHJlc3NvfGVufDB8fDB8fHww",
                            IsTrendingProduct = false,
                            Name = "Iced Coffee",
                            Price = 15m
                        });
                });

            modelBuilder.Entity("CoffeeShopp.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("CoffeeShopp.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("CoffeeShopp.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
